apiVersion: app.projectsveltos.io/v1alpha1
kind: MyKind
metadata:
  name: mykind-sample
  labels:
    app.kubernetes.io/name: kube-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  criteria: "resource.status.phase == 'Unused' || resource.status.phase == 'Unhealthy'"
  schedule: "*/1 * * * *"  # every minute for quick testing
  action: "Delete"         # Default is Delete; can be Update
  transform: "add-label: cleaned=true"
  namespaces:
    - "default"
    - "kube-system"

