apiVersion: app.projectsveltos.io/v1alpha1
kind: MyKind
metadata:
  labels:
    app.kubernetes.io/name: kube-operator
    app.kubernetes.io/managed-by: kustomize
  name: mykind-sample
spec:
  # TODO(user): Add fields here
